### ISSUE TITLE
fastfold integration

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#12]
Here's an edge case:

Suppose you open a file with `fdm=syntax`, but then issue ":set fdm=marker". Then after `:bd %`, still `w:lastfdm=syntax`. Only if an additional trigger, like saving, fold movements, or `zuz` is issued, the `fdm` is correctly restored to `marker`.

I guess `w:lastfdm` should only be saved instead of `&l:fdm` if the latter is `manual`, to exclude the case that the user manually changed but hasn't triggered any `FastFold` autocmd  before storing the view.

**Comment by kopischke** [comment]
I’ll look into that as soon as I have some time to dedicate to _vim-stay_.

**Comment by Konfekt** [comment]
Ok, that's what FastFold does in any case: Check if the current fold method is manual, and only then override it by `w:lastfdm`.

**Comment by kopischke** [comment]
I assume that after https://github.com/Konfekt/FastFold/commit/cae63341cd705660f80d10d78fc012550177cf80, this should be based on `b:lastfdm`, not `w:lastfdm`?

**Comment by Konfekt** [comment]
Yeah, lots of pushes these days. FastFold now works better assuming `fdm` being buffer local, but does so by making `w:lastfdm` equalling `b:lastfdm`. However, `w:lastfdm` is always updated first, so  `w:lastfdm` is still the more accurate option.

**Comment by kopischke** [comment]
Closed by https://github.com/kopischke/vim-stay/commit/ba35cbfe4a7ade99630ea9e0e7045991241ccb1a.

**Comment by Konfekt** [comment]
Ok, hopefully everything works as expected.
