### ISSUE TITLE
Handling of reloading through ":checktime"

### ISSUE THREAD

**Issue by blueyed** [zhimsel/vim-stay#13]
When a buffer is open in multiple windows (across multiple tabs), and the file gets changed from outside, calling `:checktime` and reloading the file will not keep the cursor position in the non-current window - it will move to the first line.

Is there anything vim-stay could do about this?

**Comment by kopischke** [comment]
If there is a suitable autocommand triggered for the reload, this should be easy to implement. I’ll see what I can do.

**Comment by kopischke** [comment]
@blueyed as a quick test, could you try modifying [line 66 of the plugin file](https://github.com/kopischke/vim-stay/blob/master/plugin/stay.vim#L66) by adding _FileChangedShellPost_ to the event list and report back if that handles `:checktime`?

**Comment by kopischke** [comment]
@blueyed this has landed in https://github.com/kopischke/vim-stay/commit/1a9c0a4b99eaeec32de34823e970da2693644cc4, scheduled for the next release provided it works as expected. Could you give the [feature/checktime](https://github.com/kopischke/vim-stay/tree/feature/checktime) branch a whirl?

**Comment by blueyed** [comment]
No, it does not help.

TEST CASE:
1. open foo.txt with multiple lines (1, 2, 3) in two windows
2. place the cursor on line 2 in the first one window, line 3 in the second
3. append to the file from outside of Vim (`echo 4 >> foo.txt`)
4. call `:checktime` in Vim

Vim asks me to load the changed file, and afterwards the cursor is moved to the first line in the non-active window.

`FileChangedShellPost` gets trigged once.

**Comment by kopischke** [comment]
I was afraid of that … seems `FileChangedShellPost` is only triggered for the active window. Hmm, that is fixable, but not as easily as I thought (_stay_ would have to iterate through all windows on that event).

**Comment by blueyed** [comment]
This might be helpful: https://github.com/blueyed/dotfiles/blob/3fc74ce43d828fc1e2233c25016ce486fc673c62/vimrc#L3262-L3272

**Comment by kopischke** [comment]
Thanks for the link. Actually, the `view#(load|make)` functions already support targeting arbitrary windows, so that part is covered.

**Comment by kopischke** [comment]
Thinking about the example you provided, if strikes me that your issue cannot be solved using view session files. Thought these are presented as scoped to the window, they are in fact bound to the specific file (there is at most one view session file per loaded file). Reloading a view in the case you described would reset all splits to the settings of the first split.

The `"` marks works on the same assumption, only saving one position per buffer, which would leave us with `winsaveview()` / `winrestview()`. Does `FileChangedShell` fire **before** the buffer is reloaded? **EDIT:** it does, but you can’t jump to other buffers when reacting to it, so that is not an option either. 

Any thoughts?

**Comment by kopischke** [comment]
Tentative solution:
1. do `winsaveview()` on top of writing a view session file every time a view is saved
2. cycle through splits with the same buffer on `FileChangedShellPost` and `winrestview()` each

@blueyed any remarks?

**Comment by blueyed** [comment]
Seems good!

**Comment by kopischke** [comment]
@blueyed I think I might have a solution for this, using Vim’s ability to save up to 9 extra view session files per buffer. Could you give the [feature/extend-scope](https://github.com/kopischke/vim-stay/tree/feature/extend-scope) branch a test run? Its interaction with `&autoread` is a bit hacky (it basically overrides it on a per-buffer basis), so I am hesitant to pull the trigger on this yet.

**Comment by blueyed** [comment]
Just tried the feature/extend-scope branch.

First there was this error:
```
"foo.txt" 8L, 16C
Error detected while processing function <SNR>44_LoadView[8]..stay#view#load:
line   37:
E119: Not enough arguments for function: s:exception2errmsg
E15: Invalid expression: "Vim error ".s:exception2errmsg()
```
caused by:
```vim
  catch /\vE48[45]/ " no read access to existing view file
    let v:errmsg  = "vim-stay could not read the view session file! "
    let v:errmsg .= "Vim error ".s:exception2errmsg()
    return -1
```

But it was gone when restarting Vim (and a (new?) view file has been created probably).

The branch appears to fix the issue (from the TEST CASE above), but threw an error before Vim asked to reload the file:
```
Error detected while processing function <SNR>44_StickyViews[24]..stay#view#make[2]..<SNR>81_
sneak2winid[1]..stay#win#gotoid[3]..<SNR>77_beam:
line    4:
E811: Not allowed to change buffer information now
```

When trying it later again, I only got (the clean) "vim-stay error E811: Not allowed to change buffer information now" for it though?!

Code reference: https://github.com/kopischke/vim-stay/blob/0031f108a315259d6aadbfed8fa65206d41de6fb/autoload/stay/win.vim#L176.

**Comment by blueyed** [comment]
This patch helps for the first issue in the previous comment:

```diff
diff --git i/autoload/stay/view.vim w/autoload/stay/view.vim
index 0fd412d..aff67b3 100644
--- i/autoload/stay/view.vim
+++ w/autoload/stay/view.vim
@@ -30,7 +30,7 @@ function! stay#view#make(winid, ...) abort
     let v:errmsg .= "Vim error ".s:exception2errmsg()
     return -1
   catch " other errors
-    let v:errmsg = 'vim-stay error '.s:exception2errmsg(v:exception)
+    let v:errmsg = 'vim-stay error '.s:exception2errmsg()
     return -1
   finally
     call s:doautocmd('User', 'BufStaySavePost')
@@ -82,10 +82,10 @@ function! stay#view#load(winid, ...) abort
     let v:errmsg .= "Vim error ".s:exception2errmsg()
     return -1
   catch /\vE%(35[0-2]|490)/ " fold errors
-    let v:errmsg = 'vim-stay error '.s:exception2errmsg(v:exception)
+    let v:errmsg = 'vim-stay error '.s:exception2errmsg()
     return 0
   catch " other errors
-    let v:errmsg = 'vim-stay error '.s:exception2errmsg(v:exception)
+    let v:errmsg = 'vim-stay error '.s:exception2errmsg()
     return -1
   finally
     " restore stale b:stay_loaded_view for API usage
@@ -116,9 +116,9 @@ function! s:sneak2winid(id) abort
   silent noautocmd keepalt keepjumps return stay#win#gotoid(a:id)
 endfunction
 
-" - extract the error message from an {exception}
-function! s:exception2errmsg(exception) abort
-  return substitute(a:exception, '\v^.{-}:\zeE\d.+$', '', '')
+" - extract the error message from v:exception
+function! s:exception2errmsg() abort
+  return substitute(v:exception, '\v^.{-}:\zeE\d.+$', '', '')
 endfunction " }}}
 
 let &cpoptions = s:cpoptions
```

**Comment by zhimsel** [comment]
@blueyed hey, sorry to awaken a long-stale issue, but:

Is this still an ongoing issue on the current `master`?

**Comment by zhimsel** [comment]
Closing this due to lack of response. @blueyed feel free to re-open this if it's still an issue.
