### ISSUE TITLE
sessionoptions

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#17]
it cost me a while to realize that `mksession` also saves folds. With vim-stay that's doubled functionality. So how about proposing 

``` vim
set sessionoptions-=folds
```

in the readme and doc?

**Comment by Konfekt** [comment]
Maybe even default to it.

**Comment by kopischke** [comment]
Not too sure about this. Sessions and views have different scopes, which is why they exist and their defaults overlap. Could you expand on your reasoning?

**Comment by Konfekt** [comment]
True, I use sessions only to conserve the latest state of my current work session, whose folds are already saved by `vim-stay`. But others might want to save folds of an older state.
