### ISSUE TITLE
getbufvar signature incompatible with vim < v7.4

### ISSUE THREAD

**Issue by amerlyq** [zhimsel/vim-stay#19]
``` bash
vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Nov 15 2012 00:31:26)
Included patches: 1-330
```

``` VimL
Error detected while processing function stay#ispersistent:                                               
line    2:                                                                                                
E118: Too many arguments for function: getbufvar                                                          
E15: Invalid expression: bufexists(a:bufnr) && !empty(l:bufpath) && getbufvar(a:bufnr, 'stay_ignore', 0) i
snot 1 && getbufvar(a:bufnr, '&buflisted') is 1 && index(['', 'acwrite'], getbufvar(a:bufnr, '&buftype')) 
isnot -1 && getbufvar(a:bufnr, '&previewwindow') isnot 1 && getbufvar(a:bufnr, '&diff') isnot 1 && index([
'', 'hide'], getbufvar(a:bufnr, '&bufhidden')) isnot -1 && filereadable(l:bufpath) && stay#isftype(a:bufnr
, a:volatile_ftypes) isnot 1 && stay#istemp(l:bufpath) isnot 1
```

**Comment by kopischke** [comment]
Ugh, yes, welcome to the wonderful world of shifting VimL method signatures and their even more wonderful documentation. As I don’t have a version of Vim behaving like that (that is one old Vim version you are running there alright :)), could you tell me what happens when you call `getbufvar()` with the name of a non-existing buffer variable?

**Comment by amerlyq** [comment]
I would liked to be able to discard that old vim too, but that damn ubuntu 12 in work's chroot...;)
I think you mean `getbufvar` and not what your asked.

``` VimL
echo getbufvar(42, "&number") --> ''
```

Old help:

``` VimL
        When the buffer or variable doesn't exist an empty string is
        returned, there is no error message.
```

**Comment by kopischke** [comment]
Year, right, `getbufvar()` was what I meant. Good news is the behaviour is unchanged in 7.4, so this should be easily fixable by ditching the default return value altogether. However, I would like to be sure this is the only incompatibility with an old Vim version: could you try deleting the third argument in the problematic line and report if _stay_ runs fine after that? If not, I might as well fix all issues in one fell swoop :).

**Comment by amerlyq** [comment]
Yes, all works. Seems like removing `, 0` on :23: didn't break anything.

**Comment by kopischke** [comment]
Well, it shouldn’t. I was more worried about some further incompatibilities – good to know there doesn’t seem to be any. Thanks for reporting and testing!

**Comment by blueyed** [comment]
Would be nice to have the fix for this releases - I've ran into this issue a few times already.
