### ISSUE TITLE
View session state intermittently gets out of sync with view

### ISSUE THREAD

**Issue by amerlyq** [zhimsel/vim-stay#24]
Sometimes I modify files when viewing/filtering -- like retab, etc.
After that I undo all changes (in some cases -- undo only after reopening file).
But `vim-stay` keeps my previous view modifications, which in unwanted behaviour.
We have only general `:CleanViewdir` command to clear all at once, but I have only one bad view.
Therefore it's needed to go into far-far-away path, search in `>1000` files for current one and delete.
Maybe, you will add convenient command like `:CleanStayCurrent` or `:CleanCurrentView`?

**Comment by kopischke** [comment]
I must admit to not seeing the need for “clearing” view state for a file, as a simple `:mkview` will update the view state at any given moment; I may be overlooking something, however, so feel free to elucidate. Either way, I would be interested in hearing how _stay_ managed to run afoul of your actual view state, as that is the one thing that is never meant to happen.

**Comment by amerlyq** [comment]
I can't exactly reproduce intermitten behaviour intentionally.
Therefore, lets this issue be opened until I catch such things again to note exact case.
Now I only know it has something to do with `set ft=...`, reindenting, `:e` and modelines. Plus sometimes `ft` empty for zsh/cpp if opening them as second file -- until I manually delete view.

**Comment by kopischke** [comment]
I see. Does just refreshing the view by doing

``` vim
:mkview | loadview
```

help?

> Therefore, lets this issue be opened until I catch such things again to note exact case.

By all means – I‘d love to get to the bottom of this.

**Comment by amerlyq** [comment]
I will try refresh view by your command when got another bug.

Also, I remember one more case -- for not keeping `:lcd` -- when I open more files in same vim session, they load their relative paths. But when I reset them manually and reload files again, new values not kept.
Of course this bug is also intermitten. Therefore wait until I could reproduce it.

**Comment by amerlyq** [comment]
Detected one case of keeping wrong filetype for buffer:
- Vim crashed with some buffer.
- You opened another file (essential), then trying to open previously crashed one.
  `:e path/to/crashed/file`
- In menu you choose Abort, then trying to open file again
- Now in menu you chooses ReadOnly.
- = Filetype is blank
- After closing buffer and reopening ReadOnly (w/o Abort) filetype is kept blank -- bug.

Similar case:
- File opened in one vim instance
- You opened another file (essential) and trying to open file already opened in another vim
- Again you press Abort, then ReadOnly -> blank filetype -> same symptoms.

As I understand now, almost all my troubles described earlier in header, are related to opening another one buffer in already running vim instance.

**Comment by amerlyq** [comment]
Second case -- not keeping manually setted pwd.
- Open two buffers (each must have already saved/generated view before that)
- If you switch between buffers -- pwd will be switched accordingly to saved values.
- Then in one buffer do `cd /som/path`
- Switch to another one and back.
- Now both buffers in current session has pwd from second buffer. 
  New pwd for first one is lost (as lost its own saved value).

Especially because of such intermitten problems, which exists on the edge of what is possible in vim, my original question was to introduce command to simply delete current view and work on as nothing happened)).

**Comment by amerlyq** [comment]
Third case -- involves default usage.
I have found the most frustraiting case, which forced me to create current issue and wish the command to remove current view. Please, try to check and confirm it -- if it possible at all to be fixed in current implementation of `vim-stay`.
- `cd /tmp && conky -C > cfg`  create some file which has modeline (use anything but vim).
- Open created `cfg` in vim. First line is `-- vim: ts=4 sw=4 noet ai cindent syntax=lua`.
- I don't like it and immediately change to `-- vim:ft=lua:ts=2:sw=2:sts=2`.
- Save, close vim and reopen file. Indent changed to 2 as intended. 
- My `vimrc` contains `expandtab` therefore I expect after replacing modeline it will restore my preffered default behaviour.
- But `noet` is kept from last modeline! It's not resetted at all! It was already saved in view on very first open!

I like that each manually changed option will be saved in view. Sometimes.
But I don't like at all to discard/overwrite all options setted wrongly from modeline, both my own and not.
Current way is irritating. I always felt it but couldn't accurately catch the reason.

Is there way to distinguish options setted by modeline from setted manually?
Maybe by comparing options in modeline and view, etc... 
I really don't know any great way.
Therefore I suggested additional option to delete view for current file.

**Comment by kopischke** [comment]
OK, so I’m not sure how to reproduce the crashed file recovery issue and I am unable to reproduce the `cd` bug you described both on master and on [the current release candidate](https://github.com/kopischke/vim-stay/tree/release/1.4.0) branch. As to your last report, unless you changed the defaults, `/tmp` should be in `&backupskip`, meaning _vim-stay_ will leave the file alone (no view session file creation or loading); could you check 
- your `&backupskip` value 
- if a view session file actually exists for the file you tested with (it should be in `&viewdir` and have a name like `=+tmp=+cfg=`)
- if it contains a `set noet` line (`cat` should do fine for this; view session files are rather short)

**Comment by kopischke** [comment]
@amerlyq Looking a bit more into the last of your reported cases, and quite independently of the fact that files in `/tmp` should never save a view, you are correct in diagnosing that stale settings from a view session file will override new modeline settings – this is now tracked in #28. Do any of the other issues have anything to do with modelines too, perchance?

**Comment by kopischke** [comment]
@amerlyq could you please tell me the output of `:echo &viewoptions`? Thanks!

**Comment by amerlyq** [comment]
As requested: `cursor,folds,localoptions,slash,unix`.
I will try to elaborate 1st and 2nd cases on most default nvim to reproduce more easily.

**Comment by kopischke** [comment]
Thanks, I guessed so: including `(local)options` in `&viewoptions` causes a lot of unexpected and hard to track issues with view session files created with that setting (see #29). Please add

``` vim
set viewoptions=folds,cursor,slash,unix
```

to your .vimrc or nvim init file and nuke your view directory by doing `:CleanViewDir` so we can be sure any issues that crop up are not related to that option.

**Comment by zhimsel** [comment]
@amerlyq is this still an issue for you?

**Comment by amerlyq** [comment]
Nope. Seems like can be closed. Thanks for ensuring ;)

**Comment by zhimsel** [comment]
Groovy, thanks. Just cleaning up all the open issues 😄
