### ISSUE TITLE
Check for sourcing of view session files is too naive

### ISSUE THREAD

**Issue by kopischke** [zhimsel/vim-stay#26]
As the Investigation into the root cause of #25 showed, recognising the sourcing of a view session file fails when `viewdir` is set to `/view//`; other corner cases may lurk in the quirks of Vim’s settings directory syntax. In such cases, `b:stay_loaded_view` is never set and `SessionLoadPost` fails to fire.

**Comment by Konfekt** [comment]
Exatamente. Allow for the double slash // at the end of viewdir. This is simple to fix though.

**Comment by kopischke** [comment]
@Konfekt my Vimdoc fu is a bit weak today … could you remind me what the double slash is meant to indicate?

**Comment by Konfekt** [comment]
It is :help 'directory'. Every view file is stored with the attached file path as a name.

**Comment by kopischke** [comment]
Ah, now I know why I didn't expect this: that particular option is meaningless for view session files, as `viewdir` is a single directory name and session files **always** have the path in their name… Be that as it may, I will see that I account for that (and similar) cases.

**Comment by Konfekt** [comment]
Ok, didn't know that. Removed all the superfluous double slashes and everything's working fine. Solved for my part.
