### ISSUE TITLE
view files for files in &backupskip 

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#32]
With

``` vim
backupskip=/tmp/*,/tmp/*,*.tmp,*~
```

vim-stay still creates a view file for the file `/tmp/mutt-linux-5msm-1000-2981-5594735571973679250`, that is there is a file

``` sh
.local/share/vim/view/=+tmp=+mutt-linux-5msm-1000-2981-5594735571973679250=
```

This happens von Vim 8.03 compiled with +wildignore and with glob2regpat() available.

**Comment by Konfekt** [comment]
This is perhaps solved by https://github.com/zhimsel/vim-stay/pull/33 ?

**Comment by zhimsel** [comment]
Correct! Thanks!
