### ISSUE TITLE
Error when using BufStayLoadPost autocmd

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#34]
With `.vimrc` as
```vim
call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/kopischke/vim-stay'
call plug#end()

autocmd User BufStayLoadPost * echomsg 'hello'
```
there appears the error message
```vim
Error detected while processing User Auto commands for "BufStayLoadPost":
E20: Mark not set
```

**Comment by kopischke** [comment]
Which versions of Vim and of _stay_ are you using?

**Comment by Konfekt** [comment]
Commit `89e5a31fcdfd39774945e61144f0022977f13365` and VIM - Vi IMproved 8.0 (2016 Sep 12)
Included patches: 1-566.

**Comment by kopischke** [comment]
That would be 1.3.1 then. Colour me surprised, as _stay_ doesn't touch Vim marks. Guessing wildly: does this only happen when there is no window visible or buffer loaded yet?

**Comment by Konfekt** [comment]
No, sorry, on every `:e file` it shows.

**Comment by kopischke** [comment]
K, will try to repro.

**Comment by zhimsel** [comment]
@Konfekt is this still occurring on the current master branch?

**Comment by Konfekt** [comment]
No, it's fine. It might have been the global `vimrc` causing this.
