### ISSUE TITLE
Slight incompatibility with Vimwiki plugin

### ISSUE THREAD

**Issue by Flurrywinde** [zhimsel/vim-stay#35]
Vimwiki maps `<cr>`, backspace, etc to its own functions, but it allows you to override this behavior by using `hasmapto`. (EDIT: What I mean is the vimwiki.vim script uses `hasmapto`, not that the user himself uses it, in case that wasn't clear.) If hasmapto sees that a mapping already exists (like if you mapped `<cr>` to something else in your .vimrc), then it won't commandeer it.

However, for some reason, this stops happening when vim-stay is installed. Now, vimwiki maps `<cr>` (and everything else it maps) regardless of whether I have my own mapping.

Any idea as to why this is happening? I'd like to fix this, as I like both plugins a lot.

**Comment by kopischke** [comment]
That sounds both very annoying and somewhat puzzling, as ~the only mapping _vim-stay_ ever comes near to is `gf`~_vim-stay_ never maps anything. Could you point me to the Vimviki repo so I can take a peek at its code?

**Comment by Flurrywinde** [comment]
https://github.com/vimwiki/vimwiki

And here's the link to my issue about this over there: https://github.com/vimwiki/vimwiki/issues/341

Note: In my original post, I didn't put put `<cr>` in backticks, so it wasn't showing up. Going to fix this now.

**Comment by kopischke** [comment]
This is most unlikely to be due to mapping conflicts as _vim-stay_ doesn’t touch mappings (I was thinking of _vim-fetch_ when I stated otherwise above). I’ll have a look at the _vimviki_ source and see if I can find anything…

**Comment by kopischke** [comment]
@Flurrywinde could you tell me what your `viewoptions` are set to (`echo &viewoptions`)?

**Comment by Flurrywinde** [comment]
`folds,options,cursor`

**Comment by kopischke** [comment]
Tentatively, I would say the inclusion of `options` is the culprit. To test this, please

1. Set `viewoptions` to the recommended default in your vimrc: `set viewoptions=cursor,folds,slash,unix`.
2. Nuke your view state with `:CleanViewdir!`.
3. Restart Vim and check a Vimviki file for mapping behaviour.

**Comment by Flurrywinde** [comment]
This worked. I guess I must have somehow missed the `viewoptions` recommended default when I installed vim-stay. Sorry about that! Thanks so much for the help.

**Comment by kopischke** [comment]
Storing options in the file state causes no end of hurt, and yeah, you are not the first user not to mind the defaults ;). I have an update for _vim-stay_ on the back burner that will mandatorily remove `options` when saving views, but I have no idea when I will get around to finalize that (life has found ways to keep me from coding for quite a while).
