### ISSUE TITLE
Can't create view folder in C:\Program Files\Vim/vimfiles/view

### ISSUE THREAD

**Issue by ghost** [zhimsel/vim-stay#37]
This should create in userhome directory instead, I use gvim 8 / 1-1214 on windows.
image [here](https://imgur.com/a/I8BgT)

**Comment by kopischke** [comment]
_vim-stay_ doesn’t decide where Vim puts viewfiles, that is a function of your `viewdir` setting. According to the Vim help, the default on Windows is `$VIM/vimfiles/view`, so I would hazard the guess your `$VIM` value is incorrect (or maybe unset?).
