### ISSUE TITLE
Add command or option to `:CleanViewdir`'s only nonexisting files.

### ISSUE THREAD

**Issue by doronbehar** [zhimsel/vim-stay#38]
Would it be possible to add a command or an option to the existing command `:CleanViewdir` that will delete only the view files which do not exist in the file-system? That will help users to clean their view dir from the garbage that may clutter there after a long time usage.

**Comment by kopischke** [comment]
Actually, that is something I planned to do when I originally implemented `CleanViewDir`. The problem with that – and the reason it is not implemented – is that the way Vim maps a file name to a view file name is an internal implementation detail the plugin cannot query. Recreating that mapping by hand would be time consuming (I’d need to verify the implementation on every platform Vim runs on), error prone (file system handling notoriously is) and very brittle (any change in Vim internals could break the feature), all things I have been trying to avoid by sticking to public interfaces while developing _stay_

As that policy has kep _vim-stay_ running pretty smoothly despite development being dormant for the last two years, I am very much unwilling to revisit this, even given the time to take up serious development of the plugin again. However, if you feel safe compromising on the aspects I noted above, you should be able to reach the same goal using a bit of shell scripting; apologies for not providing a ready made script: my `sh` and `bash` are quite rusty lately.

**Comment by doronbehar** [comment]
What do you think about [this script](https://gist.github.com/doronbehar/69e961d40f386d303bc3b6b732349a50)? It is just a draft, I can make a PR if you think the script if good and safe enough for you to distribute under your name..
