### ISSUE TITLE
vim-stay breaks vim-fetch

### ISSUE THREAD

**Issue by telotortium** [zhimsel/vim-stay#51]
See https://github.com/wsdjeg/vim-fetch/issues/34

**Comment by zhimsel** [comment]
Will happily review/accept PRs for this issue, if there's anything to be done on `vim-stay`'s side. If it needs to be addressed in `vim-fetch`, then this can be closed.

**Comment by zhimsel** [comment]
This can be re-opened if any changes to `vim-stay` need to happen.
