### ISSUE TITLE
Duplicate help tag

### ISSUE THREAD

**Issue by kopischke** [zhimsel/vim-stay#7]
Pathogen error when starting Vim:

```
Error detected while processing function pathogen#helptags:
line    4:
E154: Duplicate tag "BufStayLoadPost" in file /home/jln/.vim/bundle/vim-stay/doc/vim-stay.txt
Press ENTER or type command to continue
```

Reported by @senft in a comment to #3.

**Comment by senft** [comment]
What can I do to fix this until you release 1.2.0?

**Comment by kopischke** [comment]
You could cherry-pick https://github.com/kopischke/vim-stay/commit/b7746fc4482f7d62cebe3cb69c6c99586fd57a1e, or you could wait until tomorrow, when I release 1.2 – sorry for not doing a bug fix release sooner, I didn’t expect 1.2 to take so long.

**Comment by senft** [comment]
Alright, thanks! :+1:

**Comment by kopischke** [comment]
@senft 1.2 is up on the [releases page](https://github.com/kopischke/vim-stay/releases/tag/v1.2.0).
