### ISSUE TITLE
outsource persistency check

### ISSUE THREAD

**Issue by Konfekt** [zhimsel/vim-stay#9]
Hello,

I noticed that the persistency check is quite utile. So much that I put it in a separate file at 

https://github.com/Konfekt/FastFold/blob/master/ftdetect/persistent.vim

How about checking for the same `b:isPersistent` variable in both plugins to avoid redundancy.

I realize that for your plugin, I got to tear that check apart though into a separate `persistent` and `temp.vim` ?!

**Comment by kopischke** [comment]
Nice to see you can get so much milage out of _vim-stay_’s heuristics :). Note that you will be able to drop the last remnants of _restore_view_’s checks once release 1.2.0 is out, as I have added both an early check for an empty buffer name and a temp file check based on Vim’s `backupskip` option (there even is a new `stay#istemp()` function – so no worries about tearing stuff apart ;)).

As to `b:isPersistent`, however, and although I agree that reducing the number of similar buffer state variables would be nice, I’m not sure the coupling of our plugin’s respective logic that would ensue is a good idea. 

Just to explain what I mean by this, consider the fact that (unless I misread the code) _FastFold_’s `b:isPersistent` is **a cache** for the results of the persistency heuristics check, while _vim-stay_’s `b:stay_ignore` is **a flag** for the user to override those same heuristics. Were the two plug-ins to check for the same variable, a _vim-stay_ user installing _FastFold_ would effectively short circuit _stay_’s view management heuristics for the lifetime of a file type assignment, which I’m doubtful about as that is not in fact congruent with the lifetime of most criteria figuring in the heuristics check. To avoid that kind of unwanted side effects, we would have to sync our persistency handling logic across plug-ins – essentially making two plug-ins with entirely independent feature sets co-dependent in development. Much as I appreciate your input (and much as I hope that feeling is reciprocal), I don‘t think that kind of development co-dependency is desirable.

**Comment by Konfekt** [comment]
That's true, `b:isPersistent`'s whole point is that it's a cache. My idea was that FastFold could spare this check if loaded after vim-stay, if vim-stay just used the same variable name. How about that? Vim-stay's `b:isPersistent` will of course respect `b:stay_ignore`, and FastFold `b:isPersistent`. 

Now every plugin that uses these persistency checks, can resort to`b:isPersistent`. The actual plugin carrying out this check is that which is loaded first.

**Comment by kopischke** [comment]
Ah, I see what you are aiming at. Hmm, as I said, I don’t actually think persistence is a static buffer property, so I’m not sure I would want to cache _vim-stay_’s test result, or read a cached one for that matter. I was going to suggest you piggy-back on the `BufStay*Post` user events, but these can be triggered by direct calls of `stay#view#load()` and `stay#view#save()`, independently of the actual persistence status of the buffer. Let me think about other options for a bit.

**Comment by Konfekt** [comment]
Yeah, I overread that concern of yours but come back chastened. But, as you suggest, the `BufStayPost` event should catch all relevant persistency changes?! See  

https://github.com/Konfekt/FastFold/blob/master/ftdetect/persistent.vim#L1

This said, and having seen http://vimrcfu.com/snippet/46 , I wonder why this autocmd event is not in all ftdetect files by default?!

**Comment by kopischke** [comment]
Good to know; having slept over it, I concur the `BufStay*Post` events are your best bet. I first thought that the fact they can be triggered by direct calls to the `stay#view#*()` functions would diminish their utility in that regard, but loading and saving views is actually a pretty good indicator the user considers a buffer persistent :). So

``` vim
autocmd User BufStayLoadPost,BufStaySavePost let b:isPersistent = 1
```

should cover the offloading. I can add that to the _FastFold_ integration module if you want, that would ensure you are only listening for these events when _vim-stay_ is loaded.

As to filetype detection in `BufFilePost`, I have wondered the same thing since I stumbled on this in a PR I submitted to the _editorconfig_ plug-in: it looks like such an obvious thing to do.

**Comment by Konfekt** [comment]
Hmm.. I am reluctant because now the dependencies go back and forth between vim-stay and FastFold, because FastFold must check if vim-stay is loaded (by the existence of the BufStayLoadPost events -- How to do that?!). 

I think the idea of a universal persistency variable is sound, but `b:isPersistent` should be set by Vim itself. Perhaps we should discuss this at vim_dev or file it as an issue at its googlecode project site.

**Comment by kopischke** [comment]
True if f you mean for the variable to obviate the need for loading and setting up _FastFold_’s own detection. However, if you aim a bit lower, doing

``` vim
autocmd BufRead,BufNewFile,BufFilePost * let b:isPersistent = get(b:, 'isPersistent', s:isPersistent())
```

will avoid redundant heuristics checks, if not the need for setting them up. It also relieves _FastFold_ from knowing anything about other plug-ins setting the `b:isPersistent` variable.

You also don’t need to check for the existence of _vim-stay_ events if declaring autocommands for them happens inside the integration module for _FastFold_ _vim-stay_ provides, as per my previous comment: that module is only loaded when both plug-ins are active (or rather: will be, as of the next release; right now, it’s loaded when _vim-stay_ is active – my bad, I originally designed that module to be part of _FasFold_, _hint, hint, nudge, nudge_ :P). No cross-dependencies, just integration :).

**Comment by Konfekt** [comment]
Hmm.. I may be missing something, but does `b:isPersistent` not stay unchanged on `BufFilePost` events say with this `autocmd` (granted that `b:isPersistent` was already set on `BufRead`) ?

Ah, perhaps by defining the variable initally (BufRead, BufNewFile) at all if either plugin recognizes it as persistent. Then `FastFold` could not set `b:isPersistent = 0` any longer though, but that probably rarely happens.

**Comment by kopischke** [comment]
> I may be missing something, but does `b:isPersistent` not stay unchanged on `BufFilePost` events say with this autocmd (granted that `b:isPersistent` was already set on `BufRead`)?

Well, yes, you’d have to separate those autocommands meant to **update** persistence status from those **initializing** it, i.e.

``` vim
autocmd BufRead,BufNewFile * let b:isPersistent = get(b:, 'isPersistent', s:isPersistent())
autocmd BufFilePost        * let b:isPersistent = s:isPersistent()
```

> Then `FastFold` could not set `b:isPersistent = 0` any longer though, but that probably rarely happens.

Yes it can; see above code snippet. That would de-duplicate the initial heuristics, but keep the flexibility to re-assess wherever you feel _FastFold_ should do so. It’s not quite the cross-plug-in persistency status evaluator you were looking for initially (unless I misunderstood your intent?), but it does remove some redundancy.

**Comment by Konfekt** [comment]
Yeah, tearing the Load and Save events apart economizes the double check on the BufRead and BufNewFile Event. That's a smart move I promptly add to FastFold, see https://github.com/Konfekt/FastFold/commit/34742a6eff30417319de41fc79a60c8ef549e8f9. Thanks! 

Regarding the BufFilePost, now it occurs to me that the check by `s:persistent` is overkill but instead a buffer is persistent if written to disk. So that becomes https://github.com/Konfekt/FastFold/commit/670086cdc55d8ab662bcf5adc618dd24b81f3977

That makes me wonder: Is perhaps the simple autocmd 

```
au BufRead,BufNewFile,BufFilePost * let b:isPersistent = 1
```

even less error-prone than the check by `s:isPersistent()`?

**Comment by Konfekt** [comment]
By the way, `BufNew` should in theory already redetect the filetype on renames? The Vim help says

```
BufNew              Just after creating a new buffer.  Also used
                just after a buffer has been renamed.  When
                the buffer is added to the buffer list BufAdd
```

**Comment by kopischke** [comment]
> By the way, `BufNew` should in theory already redetect the filetype on renames?

Actually, `BufNew` detects **all** writes to another file (buffer) name, including those that do not change the current buffer, e.g. `:write another/path/and/name.ext` from `this/path/file.ext`. In the latter case it will match the new buffer name, not the original one, which means you cannot use it to trigger re-evaluation of values in the originating buffer. It’s actually in the help:

> NOTE: When this autocommand is executed, the current buffer "%" may be different from the buffer being created "<afile>".

`BufFilePost` OTOH will only trigger on the subset of these writes that renames the current file (buffer name). i.e. `:saveas` and `:file`, but not `:write`.

> That makes me wonder: Is perhaps the simple autocmd
> 
> ```
>  au BufRead,BufNewFile,BufFilePost * let b:isPersistent = 1
> ```
> 
> even less error-prone as the check by `s:isPersistent()`?

Wouldn’t think so; `BufRead` triggers on temporary and redirected files, and `BufNewFile` on new buffers without a file system equivalent – all patently not persistent.
